FROM node:18

WORKDIR /app

# Configura o crypto global
ENV NODE_OPTIONS="--experimental-global-webcrypto"

COPY package*.json ./
COPY prisma ./prisma/
RUN npm install && npx prisma generate

COPY . .
RUN npm run build

EXPOSE 3001
CMD ["npm", "run", "start:prod"]